- name: Run benchmarks
  hosts: c01.lab.dm.informatik.tu-darmstadt.de
  vars:
    benchmarks:
#      - "01_put_coalescing"
#      - "02_shuffle"
#      - "03_packet_size_put_nbi"
#      - "05_single_multi_launch"
      - "08_tuple_scan"
  tasks:
    - name: Synchronize benchmark scripts
      synchronize:
        src: "{{ item }}/run.sh"
        dest: "~/nvshmem-db/benchmarks/{{ item }}/run.sh"
        delete: true
      loop: "{{ benchmarks }}"

    - name: Run benchmark
      shell: |
        cd ~/nvshmem-db/benchmarks/{{ item }}
        ./run.sh
      register: shell_output
      loop: "{{ benchmarks }}"

    - name: Print shell output line by line
      debug:
        msg: "{{ item }}"
      loop: "{{ shell_output.results | map(attribute='stdout_lines') | list }}"

    - name: Collect results from node
      fetch:
        src: "~/nvshmem-db/benchmarks/{{ item }}/results.csv"
        dest: "tools/results/{{ item }}.csv"
        flat: yes
      loop: "{{ benchmarks }}"
