- name: Run benchmarks
  hosts: all
  vars:
    benchmarks:
      - "01_put_coalescing"
      - "02_shuffle"
  tasks:
    - name: Create project directory
      file:
        path: ~/nvshmem-db
        state: directory

    - name: Synchronize benchmarks
      synchronize:
        src: "{{ item }}"
        dest: "~/nvshmem-db/benchmarks/"
        recursive: true
        delete: true
      loop: "{{ benchmarks }}"

    - name: Synchronize other directories
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: true
        delete: true
      loop:
        - src: "CMakeLists.txt"
          dest: "~/nvshmem-db/benchmarks/"
        - src: "../inc"
          dest: "~/nvshmem-db/"
        - src: "../src"
          dest: "~/nvshmem-db/"
        - src: "../docs"
          dest: "~/nvshmem-db/"
        - src: "../test"
          dest: "~/nvshmem-db/"
        - src: "../../CMakeLists.txt"
          dest: "~/nvshmem-db/"
